spring.application.name=tykkit-backend
server.port=8080


spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.redis.host=${SPRING_REDIS_HOST}
spring.redis.port=${SPRING_REDIS_PASSWORD}
spring.redis.password=${SPRING_REDIS_PORT}
spring.redis.ssl=true
