spring.application.name=tykkit-backend
server.port=8080

#spring.data.mongodb.uri=mongodb://localhost:27017/tykkit_db
 spring.data.mongodb.uri=${MONGO_URI}
spring.redis.host=${REDIS_HOST}
spring.redis.port=${REDIS_PORT}
spring.redis.password=${REDIS_PASSWORD}

