spring.application.name=tykkit-backend
server.port=8080

spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI}
spring.mongodb.uri=${SPRING_DATA_MONGODB_URI}

# FIXED: spring.redis.* ? spring.data.redis.*
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=${SPRING_REDIS_PORT}
spring.data.redis.password=${SPRING_REDIS_PASSWORD}
spring.data.redis.ssl.enabled=${SPRING_REDIS_SSL}